# @format

name: First demo action

on:
    push:
        branches:
            - "master"

jobs:
    demo-job:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Action Started"
            - name: Checkout
              uses: actions/checkout@v4
            - name: Run a one-line script
              run: echo "hello, world!"
            - name: Run multiline script
              run: |
                  echo "Add other actions to build"
                  echo "test and deploy your project"
            - name: List files
              run: ls ${{ github.workspace}}
            - name: Print Gihub context
              env:
                  GITHUB_CONTEXT: ${{ toJson(github)}}
              run: echo "GITHUB_CONTEXT"
            - name: Action completd
              run: echo "Action completed"
